version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zerox-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017/zerox
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
    depends_on:
      - mongodb
    networks:
      - zerox-network

  mongodb:
    image: mongo:6
    container_name: zerox-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - zerox-network

networks:
  zerox-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local 